# "$schema" = "..."  # we do not support this feature yet
identifier = "default"
description = "Capability for the main window"
windows = ["main", "splash"]
permissions = [
    "core:default",
    "pytauri:default", # need for pytauri ipc
    "shell:default"
]
